/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jfram;

/**
 *
 * @author SAFEER
 */
public class calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    public calc() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        mult_btn = new javax.swing.JButton();
        sub_btn = new javax.swing.JButton();
        devi_btn = new javax.swing.JButton();
        equal_btn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        dot_btn = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        ANS_btn = new javax.swing.JButton();
        clrall_btn = new javax.swing.JButton();
        pow2_btn = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        N_or_P_btn = new javax.swing.JButton();
        sin_btn = new javax.swing.JButton();
        cos_btn = new javax.swing.JButton();
        tan_btn = new javax.swing.JButton();
        sqr_root_btn = new javax.swing.JButton();
        sin_btn1 = new javax.swing.JButton();
        cos_btn1 = new javax.swing.JButton();
        bay_btn = new javax.swing.JButton();
        approx_btn = new javax.swing.JButton();
        isDegr_btn = new javax.swing.JButton();
        BEL_btn = new javax.swing.JButton();
        log_btn = new javax.swing.JButton();
        abs_btn = new javax.swing.JButton();
        nCr_btn = new javax.swing.JButton();
        nPr_btn = new javax.swing.JButton();
        e_btn = new javax.swing.JButton();
        fac_btn = new javax.swing.JButton();
        abs_btn1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Button7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        add_btn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        add_btn.setText("+");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        mult_btn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        mult_btn.setText("*");
        mult_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mult_btnActionPerformed(evt);
            }
        });

        sub_btn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        sub_btn.setText("-");
        sub_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btnActionPerformed(evt);
            }
        });

        devi_btn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        devi_btn.setText("÷");
        devi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devi_btnActionPerformed(evt);
            }
        });

        equal_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        equal_btn.setText("=");
        equal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_btnActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        dot_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dot_btn.setText(".");
        dot_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dot_btnActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        ANS_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANS_btn.setText("ANS");
        ANS_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANS_btnActionPerformed(evt);
            }
        });

        clrall_btn.setBackground(new java.awt.Color(0, 0, 204));
        clrall_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clrall_btn.setForeground(new java.awt.Color(255, 255, 255));
        clrall_btn.setText("AC");
        clrall_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrall_btnActionPerformed(evt);
            }
        });

        pow2_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pow2_btn.setText("^2");
        pow2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pow2_btnActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        N_or_P_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        N_or_P_btn.setText("+/-");
        N_or_P_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_or_P_btnActionPerformed(evt);
            }
        });

        sin_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sin_btn.setText("sin(");
        sin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sin_btnActionPerformed(evt);
            }
        });

        cos_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cos_btn.setText("cos(");
        cos_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cos_btnActionPerformed(evt);
            }
        });

        tan_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tan_btn.setText("tan(");
        tan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tan_btnActionPerformed(evt);
            }
        });

        sqr_root_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sqr_root_btn.setText("√");
        sqr_root_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqr_root_btnActionPerformed(evt);
            }
        });

        sin_btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sin_btn1.setText("sin(");
        sin_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sin_btn1ActionPerformed(evt);
            }
        });

        cos_btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cos_btn1.setText("cos(");
        cos_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cos_btn1ActionPerformed(evt);
            }
        });

        bay_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bay_btn.setText("π");
        bay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bay_btnActionPerformed(evt);
            }
        });

        approx_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        approx_btn.setText("≈");
        approx_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approx_btnActionPerformed(evt);
            }
        });

        isDegr_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        isDegr_btn.setText("r→°");
        isDegr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isDegr_btnActionPerformed(evt);
            }
        });

        BEL_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BEL_btn.setText("DEL");
        BEL_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEL_btnActionPerformed(evt);
            }
        });

        log_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        log_btn.setText("log(");
        log_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_btnActionPerformed(evt);
            }
        });

        abs_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        abs_btn.setText("abs");
        abs_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abs_btnActionPerformed(evt);
            }
        });

        nCr_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nCr_btn.setText("nCr");
        nCr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nCr_btnActionPerformed(evt);
            }
        });

        nPr_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nPr_btn.setText("nPr");
        nPr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPr_btnActionPerformed(evt);
            }
        });

        e_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        e_btn.setText("e");
        e_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_btnActionPerformed(evt);
            }
        });

        fac_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fac_btn.setText("□!");
        fac_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac_btnActionPerformed(evt);
            }
        });

        abs_btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        abs_btn1.setText("°→r");
        abs_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abs_btn1ActionPerformed(evt);
            }
        });

        jMenu1.setText("rules");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("المساحات");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setText("المحيطات");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem3.setText("الاحجام");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sin_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cos_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(dot_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cos_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nPr_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nCr_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(approx_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N_or_P_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(log_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fac_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(tan_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(bay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sub_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mult_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(devi_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(sqr_root_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pow2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(BEL_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(clrall_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(ANS_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(equal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(abs_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(e_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(abs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(isDegr_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(isDegr_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abs_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(N_or_P_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(log_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(approx_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(e_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abs_btn1))
                    .addComponent(nPr_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nCr_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fac_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cos_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(sin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tan_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sqr_root_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pow2_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dot_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(devi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANS_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clrall_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BEL_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mult_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cos_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sin_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    double num1, num2 ,result ;
    char ope = ' ';
    
   
    public void setAll(String name)                                //to write each form of each button in text_field
    {
        String text = jTextField1.getText() + name;
        jTextField1.setText(text);
    }
   
    public void set_operation(char operation )
    {
        num1 = Double.parseDouble(jTextField1.getText());
        copy_text(operation);
        ope = operation;        
    }
    
    public void copy_text(char sign)         //to copy equation from the first txt_field to second txt_field and delete text from txt_field1
    {
        String equ = jTextField1.getText();
        jTextField2.setText(jTextField2.getText() + equ + sign );
        jTextField1.setText("");
    }
    
    public void operation_test(char operation2)
    {
        if(ope == ' ')
        {
            set_operation(operation2);
        }
    }
    
    public static double factorial(double n)
    { 
        if(n >= 0)
        {
            if (n == 0)
                return 1;
            else
            {
                return n*factorial(n-1);
            }
        }
        else
        {
             if (n == 0)
                return -1;
            else
            {
                return n*factorial(n+1);
            }
        }
    }
    
    private void devi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devi_btnActionPerformed
        operation_test('/');
        
    }//GEN-LAST:event_devi_btnActionPerformed

    private void equal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_btnActionPerformed
        
        num2 = Double.parseDouble(jTextField1.getText());
        switch(ope)
        {
            case '+':
                result = num1 + num2;
                jTextField1.setText(String.valueOf(result));
                jTextField2.setText(jTextField2.getText() + num2 + " -> " );
                break;
            case '-':
                result = num1 - num2;
                jTextField1.setText(String.valueOf(result));
                jTextField2.setText(jTextField2.getText() + num2 + " -> " );
                break;
            case '*':
                result = num1 * num2;
                jTextField1.setText(String.valueOf(result));
                jTextField2.setText(jTextField2.getText() + num2 + " -> " );
                break;
            case '/':
                if(num1 != 0 && num2 == 0 )
                {
                    jTextField2.setText("");
                    jTextField1.setText("math Error!");
                    break;
                }
                if(num1 == 0 && num2 == 0)
                {
                   jTextField2.setText("");
                   jTextField1.setText("math Error!");
                   break; 
                }
                    
                result = num1 / num2;
                jTextField1.setText(String.valueOf(result));
                jTextField2.setText(jTextField2.getText() + num2 + " -> " );
                break;
                
        }
        
        ope = ' ';
        
        
    }//GEN-LAST:event_equal_btnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setAll("1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dot_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dot_btnActionPerformed
        setAll(".");
    }//GEN-LAST:event_dot_btnActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        setAll("0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void ANS_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANS_btnActionPerformed
        jTextField1.setText(String.valueOf(result));
    }//GEN-LAST:event_ANS_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setAll("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setAll("3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        setAll("4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        setAll("5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        setAll("6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        setAll("7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        setAll("8");
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
       setAll("9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void clrall_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrall_btnActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        ope = ' ';
    }//GEN-LAST:event_clrall_btnActionPerformed

    
    private void pow2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pow2_btnActionPerformed
     double res = Double.parseDouble(jTextField1.getText());
     jTextField1.setText(String.valueOf(Math.pow(res, 2)));
    }//GEN-LAST:event_pow2_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        operation_test('+');
    }//GEN-LAST:event_add_btnActionPerformed

    private void sub_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btnActionPerformed
        operation_test('-');
    }//GEN-LAST:event_sub_btnActionPerformed

    private void mult_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mult_btnActionPerformed
        operation_test('*');
    }//GEN-LAST:event_mult_btnActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
                            
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void N_or_P_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_or_P_btnActionPerformed
        double var = Double.parseDouble(jTextField1.getText());
        var = var * -1;
        jTextField1.setText(String.valueOf(var));
    }//GEN-LAST:event_N_or_P_btnActionPerformed

    private void sin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sin_btnActionPerformed
        double res = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(String.valueOf(Math.sin(Math.toRadians(res))));
    }//GEN-LAST:event_sin_btnActionPerformed

    private void cos_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cos_btnActionPerformed
         double res = Double.parseDouble(jTextField1.getText());
         jTextField1.setText(String.valueOf(Math.cos(Math.toRadians(res))));
    }//GEN-LAST:event_cos_btnActionPerformed

    private void tan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tan_btnActionPerformed
         double res = Double.parseDouble(jTextField1.getText());
         jTextField1.setText(String.valueOf(Math.tan(Math.toRadians(res))));
    }//GEN-LAST:event_tan_btnActionPerformed

    private void sqr_root_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqr_root_btnActionPerformed
         double res = Double.parseDouble(jTextField1.getText());
         if(res < 0)
         {
             jTextField1.setText("math Error!");
             jTextField2.setText("");
         }
         else
            jTextField1.setText(String.valueOf(Math.sqrt(res)));
    }//GEN-LAST:event_sqr_root_btnActionPerformed

    private void sin_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sin_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sin_btn1ActionPerformed

    private void cos_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cos_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cos_btn1ActionPerformed

    private void bay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bay_btnActionPerformed
        setAll(String.valueOf(Math.PI));
    }//GEN-LAST:event_bay_btnActionPerformed

    private void approx_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approx_btnActionPerformed
        double number = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(String.valueOf(Math.round(number)));
    }//GEN-LAST:event_approx_btnActionPerformed

    private void isDegr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isDegr_btnActionPerformed
        double number = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(String.valueOf(Math.toDegrees(number)));

    }//GEN-LAST:event_isDegr_btnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       Areas areas = new Areas();
       areas.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Perimeter perimeter = new Perimeter();
        perimeter.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Size size = new Size();
        size.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void BEL_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEL_btnActionPerformed
        String BS = null;
        
        if (jTextField1.getText().length() > 0 )
        {
            StringBuilder s = new StringBuilder(jTextField1.getText());
            s.deleteCharAt(jTextField1.getText().length() - 1);
            BS = s.toString();
            jTextField1.setText(BS);
            
        }
    }//GEN-LAST:event_BEL_btnActionPerformed

    private void log_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_btnActionPerformed
        double number = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(String.valueOf(Math.log10(number)));
    }//GEN-LAST:event_log_btnActionPerformed

    private void abs_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abs_btnActionPerformed
        double number = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(String.valueOf(Math.abs(number)));
    }//GEN-LAST:event_abs_btnActionPerformed

    private void nCr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nCr_btnActionPerformed
         double res = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(String.valueOf(Math.acos(res)));
    }//GEN-LAST:event_nCr_btnActionPerformed

    private void nPr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPr_btnActionPerformed
         //double res = Double.parseDouble(jTextField1.getText());
        //jTextField1.setText(String.valueOf());
    }//GEN-LAST:event_nPr_btnActionPerformed

    private void e_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_btnActionPerformed
        setAll(String.valueOf(Math.E));
    }//GEN-LAST:event_e_btnActionPerformed

    private void fac_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac_btnActionPerformed
         double res = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(String.valueOf(factorial(res)));
    }//GEN-LAST:event_fac_btnActionPerformed

    private void abs_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abs_btn1ActionPerformed
    double number = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(String.valueOf(Math.toRadians(number)));
    }//GEN-LAST:event_abs_btn1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANS_btn;
    private javax.swing.JButton BEL_btn;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton N_or_P_btn;
    private javax.swing.JButton abs_btn;
    private javax.swing.JButton abs_btn1;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton approx_btn;
    private javax.swing.JButton bay_btn;
    private javax.swing.JButton clrall_btn;
    private javax.swing.JButton cos_btn;
    private javax.swing.JButton cos_btn1;
    private javax.swing.JButton devi_btn;
    private javax.swing.JButton dot_btn;
    private javax.swing.JButton e_btn;
    private javax.swing.JButton equal_btn;
    private javax.swing.JButton fac_btn;
    private javax.swing.JButton isDegr_btn;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton log_btn;
    private javax.swing.JButton mult_btn;
    private javax.swing.JButton nCr_btn;
    private javax.swing.JButton nPr_btn;
    private javax.swing.JButton pow2_btn;
    private javax.swing.JButton sin_btn;
    private javax.swing.JButton sin_btn1;
    private javax.swing.JButton sqr_root_btn;
    private javax.swing.JButton sub_btn;
    private javax.swing.JButton tan_btn;
    // End of variables declaration//GEN-END:variables
}
